# Generated by Django 5.0.1 on 2024-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_urls', models.TextField()),
                ('short_urls', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
